# Generated by Django 2.2.4 on 2019-08-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_app', '0002_auto_20190825_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.FloatField(),
        ),
    ]
